/* Generated by Yosys 0.13+10 (git sha1 UNKNOWN, ccache clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "gates/redstone.sv:10.1-38.10" *)
module repeater(in, latch, out);
  (* src = "gates/redstone.sv:30.3-37.6" *)
  wire _00_;
  (* src = "gates/redstone.sv:30.3-37.6" *)
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "gates/redstone.sv:13.18-13.20" *)
  (* wiretype = "\\redstone" *)
  input [3:0] in;
  (* src = "gates/redstone.sv:14.9-14.14" *)
  input latch;
  (* src = "gates/redstone.sv:15.19-15.22" *)
  (* wiretype = "\\redstone" *)
  output [3:0] out;
  (* init = 1'h0 *)
  (* src = "gates/redstone.sv:18.7-18.20" *)
  wire should_output;
  (* src = "gates/redstone.sv:20.31-20.36" *)
  wire state;
  (* init = 8'h01 *)
  (* src = "gates/redstone.sv:17.8-17.21" *)
  wire [7:0] time_sense_on;
  inv _37_ (
    .A(time_sense_on[3]),
    .Y(_02_)
  );
  inv _38_ (
    .A(time_sense_on[7]),
    .Y(_03_)
  );
  inv _39_ (
    .A(time_sense_on[0]),
    .Y(_04_)
  );
  nor2 _40_ (
    .A(time_sense_on[2]),
    .B(time_sense_on[1]),
    .Y(_05_)
  );
  nand2 _41_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  nor2 _42_ (
    .A(time_sense_on[6]),
    .B(time_sense_on[5]),
    .Y(_07_)
  );
  nor2 _43_ (
    .A(time_sense_on[4]),
    .B(time_sense_on[3]),
    .Y(_08_)
  );
  nand2 _44_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  oai211 _45_ (
    .A(_06_),
    .B(_09_),
    .C(_03_),
    .Y(_00_)
  );
  nor2 _46_ (
    .A(_03_),
    .B(_04_),
    .Y(_10_)
  );
  nor2 _47_ (
    .A(in[1]),
    .B(in[0]),
    .Y(_11_)
  );
  inv _48_ (
    .A(_11_),
    .Y(_12_)
  );
  nor2 _49_ (
    .A(in[3]),
    .B(in[2]),
    .Y(_13_)
  );
  inv _50_ (
    .A(_13_),
    .Y(_14_)
  );
  nor2 _51_ (
    .A(_12_),
    .B(_14_),
    .Y(_15_)
  );
  oai211 _52_ (
    .A(time_sense_on[0]),
    .B(_00_),
    .C(_15_),
    .Y(_16_)
  );
  nor2 _53_ (
    .A(_10_),
    .B(_16_),
    .Y(_01_[0])
  );
  oai211 _54_ (
    .A(time_sense_on[1]),
    .B(_10_),
    .C(_15_),
    .Y(_17_)
  );
  aoi211 _55_ (
    .A(time_sense_on[1]),
    .B(_10_),
    .C(_17_),
    .Y(_01_[1])
  );
  aoi211 _56_ (
    .A(time_sense_on[1]),
    .B(_10_),
    .C(time_sense_on[2]),
    .Y(_18_)
  );
  nand2 _57_ (
    .A(time_sense_on[2]),
    .B(time_sense_on[1]),
    .Y(_19_)
  );
  nor2 _58_ (
    .A(_04_),
    .B(_19_),
    .Y(_20_)
  );
  nand2 _59_ (
    .A(_00_),
    .B(_20_),
    .Y(_21_)
  );
  inv _60_ (
    .A(_21_),
    .Y(_22_)
  );
  nand2 _61_ (
    .A(_15_),
    .B(_21_),
    .Y(_23_)
  );
  nor2 _62_ (
    .A(_18_),
    .B(_23_),
    .Y(_01_[2])
  );
  nor2 _63_ (
    .A(_02_),
    .B(_21_),
    .Y(_24_)
  );
  oai211 _64_ (
    .A(time_sense_on[3]),
    .B(_22_),
    .C(_15_),
    .Y(_25_)
  );
  nor2 _65_ (
    .A(_24_),
    .B(_25_),
    .Y(_01_[3])
  );
  oai211 _66_ (
    .A(time_sense_on[4]),
    .B(_24_),
    .C(_15_),
    .Y(_26_)
  );
  aoi211 _67_ (
    .A(time_sense_on[4]),
    .B(_24_),
    .C(_26_),
    .Y(_01_[4])
  );
  aoi211 _68_ (
    .A(time_sense_on[4]),
    .B(_24_),
    .C(time_sense_on[5]),
    .Y(_27_)
  );
  nand2 _69_ (
    .A(time_sense_on[5]),
    .B(time_sense_on[4]),
    .Y(_28_)
  );
  inv _70_ (
    .A(_28_),
    .Y(_29_)
  );
  nand2 _71_ (
    .A(time_sense_on[3]),
    .B(_29_),
    .Y(_30_)
  );
  nor2 _72_ (
    .A(_21_),
    .B(_30_),
    .Y(_31_)
  );
  oai211 _73_ (
    .A(_21_),
    .B(_30_),
    .C(_15_),
    .Y(_32_)
  );
  nor2 _74_ (
    .A(_27_),
    .B(_32_),
    .Y(_01_[5])
  );
  nand2 _75_ (
    .A(time_sense_on[6]),
    .B(_20_),
    .Y(_33_)
  );
  nor2 _76_ (
    .A(_30_),
    .B(_33_),
    .Y(_34_)
  );
  oai211 _77_ (
    .A(time_sense_on[6]),
    .B(_31_),
    .C(_15_),
    .Y(_35_)
  );
  aoi211 _78_ (
    .A(_00_),
    .B(_34_),
    .C(_35_),
    .Y(_01_[6])
  );
  nand2 _79_ (
    .A(time_sense_on[7]),
    .B(_15_),
    .Y(_36_)
  );
  nor2 _80_ (
    .A(_34_),
    .B(_36_),
    .Y(_01_[7])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _81_ (
    .D(_00_),
    .Q(should_output)
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _82_ (
    .D(_01_[0]),
    .Q(time_sense_on[0])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _83_ (
    .D(_01_[1]),
    .Q(time_sense_on[1])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _84_ (
    .D(_01_[2]),
    .Q(time_sense_on[2])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _85_ (
    .D(_01_[3]),
    .Q(time_sense_on[3])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _86_ (
    .D(_01_[4]),
    .Q(time_sense_on[4])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _87_ (
    .D(_01_[5]),
    .Q(time_sense_on[5])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _88_ (
    .D(_01_[6]),
    .Q(time_sense_on[6])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _89_ (
    .D(_01_[7]),
    .Q(time_sense_on[7])
  );
  assign out = { 3'h0, should_output };
  assign state = should_output;
endmodule
