/* Generated by Yosys 0.13+10 (git sha1 UNKNOWN, ccache clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "gates/redstone.sv:10.1-38.10" *)
module repeater(in, latch, out);
  (* src = "gates/redstone.sv:30.3-37.6" *)
  wire _00_;
  (* src = "gates/redstone.sv:30.3-37.6" *)
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "gates/redstone.sv:13.18-13.20" *)
  (* wiretype = "\\redstone" *)
  input [3:0] in;
  (* src = "gates/redstone.sv:14.9-14.14" *)
  input latch;
  (* src = "gates/redstone.sv:15.19-15.22" *)
  (* wiretype = "\\redstone" *)
  output [3:0] out;
  (* init = 1'h0 *)
  (* src = "gates/redstone.sv:18.7-18.20" *)
  wire should_output;
  (* src = "gates/redstone.sv:20.31-20.36" *)
  wire state;
  (* init = 8'h01 *)
  (* src = "gates/redstone.sv:17.8-17.21" *)
  wire [7:0] time_sense_on;
  \Y=!A  _24_ (
    .A(time_sense_on[6]),
    .Y(_02_)
  );
  \Y=!A  _25_ (
    .A(time_sense_on[5]),
    .Y(_03_)
  );
  \Y=!A  _26_ (
    .A(time_sense_on[7]),
    .Y(_04_)
  );
  \Y=!A  _27_ (
    .A(time_sense_on[0]),
    .Y(_05_)
  );
  \Y=!(A+B+C)  _28_ (
    .A(time_sense_on[2]),
    .B(time_sense_on[1]),
    .C(time_sense_on[0]),
    .Y(_06_)
  );
  \Y=!(A+B+C+D)  _29_ (
    .A(time_sense_on[6]),
    .B(time_sense_on[5]),
    .C(time_sense_on[4]),
    .D(time_sense_on[3]),
    .Y(_07_)
  );
  \Y=(A&B)+!C  _30_ (
    .A(_06_),
    .B(_07_),
    .C(_04_),
    .Y(_00_)
  );
  \Y=(A&B)+!(C&D)  _31_ (
    .A(_06_),
    .B(_07_),
    .C(_04_),
    .D(_05_),
    .Y(_08_)
  );
  \Y=!(A+B+C+D)  _32_ (
    .A(in[1]),
    .B(in[0]),
    .C(in[3]),
    .D(in[2]),
    .Y(_09_)
  );
  \Y=!(!(A&B)+(C&D))  _33_ (
    .A(_08_),
    .B(_09_),
    .C(time_sense_on[7]),
    .D(time_sense_on[0]),
    .Y(_01_[0])
  );
  \Y=A&B&C  _34_ (
    .A(time_sense_on[1]),
    .B(time_sense_on[7]),
    .C(time_sense_on[0]),
    .Y(_10_)
  );
  \Y=(A&B)+C  _35_ (
    .A(time_sense_on[7]),
    .B(time_sense_on[0]),
    .C(time_sense_on[1]),
    .Y(_11_)
  );
  \Y=!(A&B)  _36_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  \Y=!(A+B)  _37_ (
    .A(_10_),
    .B(_12_),
    .Y(_01_[1])
  );
  \Y=A&B  _38_ (
    .A(time_sense_on[2]),
    .B(time_sense_on[0]),
    .Y(_13_)
  );
  \Y=A&B  _39_ (
    .A(time_sense_on[1]),
    .B(_13_),
    .Y(_14_)
  );
  \Y=!(!(A&B)+!(C&D))  _40_ (
    .A(time_sense_on[2]),
    .B(time_sense_on[1]),
    .C(time_sense_on[7]),
    .D(time_sense_on[0]),
    .Y(_15_)
  );
  \Y=!((A+B)&C)  _41_ (
    .A(time_sense_on[2]),
    .B(_10_),
    .C(_09_),
    .Y(_16_)
  );
  \Y=!(A+B)  _42_ (
    .A(_15_),
    .B(_16_),
    .Y(_01_[2])
  );
  \Y=A&B  _43_ (
    .A(time_sense_on[3]),
    .B(_15_),
    .Y(_17_)
  );
  \Y=!((A+B)&C)  _44_ (
    .A(time_sense_on[3]),
    .B(_15_),
    .C(_09_),
    .Y(_18_)
  );
  \Y=!(A+B)  _45_ (
    .A(_17_),
    .B(_18_),
    .Y(_01_[3])
  );
  \Y=!(A&B&C)  _46_ (
    .A(time_sense_on[4]),
    .B(time_sense_on[3]),
    .C(_15_),
    .Y(_19_)
  );
  \Y=(A&B)+C  _47_ (
    .A(time_sense_on[3]),
    .B(_15_),
    .C(time_sense_on[4]),
    .Y(_20_)
  );
  \Y=A&B&C  _48_ (
    .A(_09_),
    .B(_19_),
    .C(_20_),
    .Y(_01_[4])
  );
  \Y=!(A&B&C&D)  _49_ (
    .A(time_sense_on[5]),
    .B(time_sense_on[4]),
    .C(time_sense_on[3]),
    .D(_15_),
    .Y(_21_)
  );
  \Y=!(!(A&B)+(C&D))  _50_ (
    .A(_09_),
    .B(_21_),
    .C(_19_),
    .D(_03_),
    .Y(_01_[5])
  );
  \Y=!(!(A&B)+!(C&D))  _51_ (
    .A(time_sense_on[6]),
    .B(time_sense_on[5]),
    .C(time_sense_on[4]),
    .D(time_sense_on[3]),
    .Y(_22_)
  );
  \Y=!(A&B&C&D)  _52_ (
    .A(time_sense_on[1]),
    .B(time_sense_on[7]),
    .C(_13_),
    .D(_22_),
    .Y(_23_)
  );
  \Y=!(!(A&B)+(C&D))  _53_ (
    .A(_09_),
    .B(_23_),
    .C(_21_),
    .D(_02_),
    .Y(_01_[6])
  );
  \Y=!(!(A&B)+(C&D))  _54_ (
    .A(time_sense_on[7]),
    .B(_09_),
    .C(_14_),
    .D(_22_),
    .Y(_01_[7])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _55_ (
    .D(_00_),
    .Q(should_output)
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _56_ (
    .D(_01_[0]),
    .Q(time_sense_on[0])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _57_ (
    .D(_01_[1]),
    .Q(time_sense_on[1])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _58_ (
    .D(_01_[2]),
    .Q(time_sense_on[2])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _59_ (
    .D(_01_[3]),
    .Q(time_sense_on[3])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _60_ (
    .D(_01_[4]),
    .Q(time_sense_on[4])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _61_ (
    .D(_01_[5]),
    .Q(time_sense_on[5])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _62_ (
    .D(_01_[6]),
    .Q(time_sense_on[6])
  );
  (* src = "gates/redstone.sv:30.3-37.6" *)
  \$_FF_  _63_ (
    .D(_01_[7]),
    .Q(time_sense_on[7])
  );
  assign out = { 3'h0, should_output };
  assign state = should_output;
endmodule
