/* Generated by Yosys 0.13+10 (git sha1 UNKNOWN, ccache clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "pong.sv:69.1-122.10" *)
module pong(clk, reset, in_control_1, in_control_2, in_paddle_1_pos, in_paddle_2_pos, out_paddle_1_pos, out_paddle_2_pos, in_score_p1, in_score_p2, in_ball_vel_y, in_ball_vel_x, out_score_p1, out_score_p2, in_ball_pos_x, in_ball_pos_y, out_ball_pos_x, out_ball_pos_y, bounce);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "pong.sv:113.10-113.28" *)
  wire ball_bounce_paddle;
  (* src = "pong.sv:79.17-79.23" *)
  output bounce;
  (* src = "pong.sv:81.23-81.40" *)
  wire [7:0] bounce_ball_pos_x;
  (* src = "pong.sv:81.42-81.59" *)
  wire [7:0] bounce_ball_pos_y;
  (* src = "pong.sv:103.17-103.30" *)
  (* unused_bits = "0" *)
  wire bounce_ball_x;
  (* src = "pong.sv:95.17-95.30" *)
  (* unused_bits = "0" *)
  wire bounce_ball_y;
  (* hdlname = "bouncer_ball_x bounce" *)
  (* src = "pong.sv:100.13-106.6|pong.sv:38.12-38.18" *)
  (* unused_bits = "0" *)
  wire \bouncer_ball_x.bounce ;
  (* hdlname = "bouncer_ball_x in_pos" *)
  (* src = "pong.sv:100.13-106.6|pong.sv:36.24-36.30" *)
  wire [7:0] \bouncer_ball_x.in_pos ;
  (* hdlname = "bouncer_ball_x in_vel" *)
  (* src = "pong.sv:100.13-106.6|pong.sv:37.24-37.30" *)
  wire [3:0] \bouncer_ball_x.in_vel ;
  (* hdlname = "bouncer_ball_x near_bound" *)
  (* src = "pong.sv:100.13-106.6|pong.sv:47.16-47.26" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] \bouncer_ball_x.near_bound ;
  (* hdlname = "bouncer_ball_x out_pos" *)
  (* src = "pong.sv:100.13-106.6|pong.sv:39.25-39.32" *)
  wire [7:0] \bouncer_ball_x.out_pos ;
  (* hdlname = "bouncer_ball_y bounce" *)
  (* src = "pong.sv:92.13-98.6|pong.sv:38.12-38.18" *)
  (* unused_bits = "0" *)
  wire \bouncer_ball_y.bounce ;
  (* hdlname = "bouncer_ball_y in_pos" *)
  (* src = "pong.sv:92.13-98.6|pong.sv:36.24-36.30" *)
  wire [7:0] \bouncer_ball_y.in_pos ;
  (* hdlname = "bouncer_ball_y in_vel" *)
  (* src = "pong.sv:92.13-98.6|pong.sv:37.24-37.30" *)
  wire [3:0] \bouncer_ball_y.in_vel ;
  (* hdlname = "bouncer_ball_y near_bound" *)
  (* src = "pong.sv:92.13-98.6|pong.sv:47.16-47.26" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] \bouncer_ball_y.near_bound ;
  (* hdlname = "bouncer_ball_y out_pos" *)
  (* src = "pong.sv:92.13-98.6|pong.sv:39.25-39.32" *)
  wire [7:0] \bouncer_ball_y.out_pos ;
  (* src = "pong.sv:70.11-70.14" *)
  input clk;
  (* src = "pong.sv:115.10-115.21" *)
  wire gutter_ball;
  (* src = "pong.sv:77.23-77.36" *)
  input [7:0] in_ball_pos_x;
  (* src = "pong.sv:77.38-77.51" *)
  input [7:0] in_ball_pos_y;
  (* src = "pong.sv:75.32-75.45" *)
  input [3:0] in_ball_vel_x;
  (* src = "pong.sv:75.17-75.30" *)
  input [3:0] in_ball_vel_y;
  (* src = "pong.sv:71.24-71.36" *)
  input [1:0] in_control_1;
  (* src = "pong.sv:71.38-71.50" *)
  input [1:0] in_control_2;
  (* src = "pong.sv:72.24-72.39" *)
  input [7:0] in_paddle_1_pos;
  (* src = "pong.sv:72.41-72.56" *)
  input [7:0] in_paddle_2_pos;
  (* src = "pong.sv:74.17-74.28" *)
  input [3:0] in_score_p1;
  (* src = "pong.sv:74.30-74.41" *)
  input [3:0] in_score_p2;
  (* src = "pong.sv:78.25-78.39" *)
  output [7:0] out_ball_pos_x;
  (* src = "pong.sv:78.41-78.55" *)
  output [7:0] out_ball_pos_y;
  (* src = "pong.sv:73.25-73.41" *)
  output [7:0] out_paddle_1_pos;
  (* src = "pong.sv:73.43-73.59" *)
  output [7:0] out_paddle_2_pos;
  (* src = "pong.sv:76.18-76.30" *)
  output [3:0] out_score_p1;
  (* src = "pong.sv:76.32-76.44" *)
  output [3:0] out_score_p2;
  (* hdlname = "paddle1 bouncer_paddle bounce" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:38.12-38.18|pong.sv:62.13-66.6" *)
  wire \paddle1.bouncer_paddle.bounce ;
  (* hdlname = "paddle1 bouncer_paddle in_pos" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:36.24-36.30|pong.sv:62.13-66.6" *)
  wire [7:0] \paddle1.bouncer_paddle.in_pos ;
  (* hdlname = "paddle1 bouncer_paddle in_vel" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:37.24-37.30|pong.sv:62.13-66.6" *)
  wire [3:0] \paddle1.bouncer_paddle.in_vel ;
  (* hdlname = "paddle1 bouncer_paddle near_bound" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:47.16-47.26|pong.sv:62.13-66.6" *)
  wire [7:0] \paddle1.bouncer_paddle.near_bound ;
  (* hdlname = "paddle1 bouncer_paddle new_pos" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:42.23-42.30|pong.sv:62.13-66.6" *)
  wire [7:0] \paddle1.bouncer_paddle.new_pos ;
  (* hdlname = "paddle1 bouncer_paddle out_pos" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:39.25-39.32|pong.sv:62.13-66.6" *)
  wire [7:0] \paddle1.bouncer_paddle.out_pos ;
  (* hdlname = "paddle1 in_control" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:57.24-57.34" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \paddle1.in_control ;
  (* hdlname = "paddle1 in_control_1" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:61.36-61.48" *)
  wire \paddle1.in_control_1 ;
  (* hdlname = "paddle1 in_pos" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:58.24-58.30" *)
  wire [7:0] \paddle1.in_pos ;
  (* hdlname = "paddle1 in_vel" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:61.23-61.29" *)
  wire [3:0] \paddle1.in_vel ;
  (* hdlname = "paddle1 out_pos" *)
  (* src = "pong.sv:86.12-90.10|pong.sv:59.25-59.32" *)
  wire [7:0] \paddle1.out_pos ;
  (* src = "pong.sv:70.16-70.21" *)
  input reset;
  assign _025_ = ~in_ball_pos_y[6];
  assign _026_ = ~in_ball_pos_x[6];
  assign _027_ = in_ball_vel_y[0] & in_ball_pos_y[0];
  assign _028_ = ~(in_ball_vel_y[0] ^ in_ball_pos_y[0]);
  assign _029_ = in_ball_vel_y[3] | ~(in_ball_pos_y[6]);
  assign _030_ = in_ball_pos_y[5] | in_ball_vel_y[3];
  assign _031_ = ~(in_ball_pos_y[5] & in_ball_vel_y[3]);
  assign _032_ = ~(in_ball_pos_y[4] & in_ball_vel_y[3]);
  assign _033_ = in_ball_pos_y[4] ^ in_ball_vel_y[3];
  assign _034_ = ~(in_ball_pos_y[3] & in_ball_vel_y[3]);
  assign _035_ = in_ball_pos_y[3] | in_ball_vel_y[3];
  assign _036_ = ~(in_ball_pos_y[2] & in_ball_vel_y[2]);
  assign _037_ = in_ball_pos_y[2] ^ in_ball_vel_y[2];
  assign _038_ = ~(in_ball_pos_y[1] & in_ball_vel_y[1]);
  assign _039_ = in_ball_pos_y[1] ^ in_ball_vel_y[1];
  assign _040_ = ~(_027_ & _039_);
  assign _041_ = ~(_038_ & _040_);
  assign _042_ = ~(_037_ & _041_);
  assign _043_ = ~(_036_ & _042_);
  assign _044_ = ~(_035_ & _043_);
  assign _045_ = ~(_034_ & _044_);
  assign _046_ = ~(_033_ & _045_);
  assign _047_ = _032_ & _046_;
  assign _048_ = ~(_031_ & _047_);
  assign _049_ = _030_ & _048_;
  assign _050_ = in_ball_pos_y[6] | ~(in_ball_vel_y[3]);
  assign _051_ = in_ball_vel_y[3] ? _048_ : _025_;
  assign _052_ = in_ball_pos_y[6] & ~(_049_);
  assign _053_ = _051_ | _052_;
  assign out_ball_pos_y[0] = ~(_028_ & _053_);
  assign _054_ = _053_ | ~(in_ball_pos_y[7]);
  assign _055_ = _027_ ^ _039_;
  assign out_ball_pos_y[1] = _053_ ? _055_ : in_ball_pos_y[7];
  assign _056_ = _037_ ^ _041_;
  assign out_ball_pos_y[2] = _053_ ? _056_ : in_ball_pos_y[7];
  assign _057_ = ~(_034_ & _035_);
  assign _058_ = ~(_043_ ^ _057_);
  assign out_ball_pos_y[3] = _053_ ? _058_ : in_ball_pos_y[7];
  assign _059_ = _033_ ^ _045_;
  assign out_ball_pos_y[4] = _053_ ? _059_ : in_ball_pos_y[7];
  assign _060_ = _030_ & _031_;
  assign _061_ = ~(_047_ ^ _060_);
  assign out_ball_pos_y[5] = _053_ ? _061_ : in_ball_pos_y[7];
  assign _062_ = ~(_049_ & _050_);
  assign _063_ = _029_ ? _062_ : _049_;
  assign out_ball_pos_y[6] = ~(_054_ & _063_);
  assign _064_ = in_ball_vel_x[0] & in_ball_pos_x[0];
  assign _065_ = ~(in_ball_vel_x[0] ^ in_ball_pos_x[0]);
  assign _066_ = in_ball_vel_x[3] | ~(in_ball_pos_x[6]);
  assign _067_ = in_ball_pos_x[5] | in_ball_vel_x[3];
  assign _068_ = ~(in_ball_pos_x[5] & in_ball_vel_x[3]);
  assign _069_ = ~(in_ball_pos_x[4] & in_ball_vel_x[3]);
  assign _070_ = in_ball_pos_x[4] ^ in_ball_vel_x[3];
  assign _071_ = ~(in_ball_pos_x[3] & in_ball_vel_x[3]);
  assign _072_ = in_ball_pos_x[3] | in_ball_vel_x[3];
  assign _073_ = ~(in_ball_pos_x[2] & in_ball_vel_x[2]);
  assign _074_ = in_ball_pos_x[2] ^ in_ball_vel_x[2];
  assign _075_ = ~(in_ball_pos_x[1] & in_ball_vel_x[1]);
  assign _000_ = in_ball_pos_x[1] ^ in_ball_vel_x[1];
  assign _001_ = ~(_064_ & _000_);
  assign _002_ = ~(_075_ & _001_);
  assign _003_ = ~(_074_ & _002_);
  assign _004_ = ~(_073_ & _003_);
  assign _005_ = ~(_072_ & _004_);
  assign _006_ = ~(_071_ & _005_);
  assign _007_ = ~(_070_ & _006_);
  assign _008_ = _069_ & _007_;
  assign _009_ = ~(_068_ & _008_);
  assign _010_ = _067_ & _009_;
  assign _011_ = in_ball_pos_x[6] | ~(in_ball_vel_x[3]);
  assign _012_ = in_ball_vel_x[3] ? _009_ : _026_;
  assign _013_ = in_ball_pos_x[6] & ~(_010_);
  assign _014_ = _012_ | _013_;
  assign out_ball_pos_x[0] = ~(_065_ & _014_);
  assign _015_ = _014_ | ~(in_ball_pos_x[7]);
  assign _016_ = _064_ ^ _000_;
  assign out_ball_pos_x[1] = _014_ ? _016_ : in_ball_pos_x[7];
  assign _017_ = _074_ ^ _002_;
  assign out_ball_pos_x[2] = _014_ ? _017_ : in_ball_pos_x[7];
  assign _018_ = ~(_071_ & _072_);
  assign _019_ = ~(_004_ ^ _018_);
  assign out_ball_pos_x[3] = _014_ ? _019_ : in_ball_pos_x[7];
  assign _020_ = _070_ ^ _006_;
  assign out_ball_pos_x[4] = _014_ ? _020_ : in_ball_pos_x[7];
  assign _021_ = _067_ & _068_;
  assign _022_ = ~(_008_ ^ _021_);
  assign out_ball_pos_x[5] = _014_ ? _022_ : in_ball_pos_x[7];
  assign _023_ = ~(_010_ & _011_);
  assign _024_ = _066_ ? _023_ : _010_;
  assign out_ball_pos_x[6] = ~(_015_ & _024_);
  assign bounce = ~(_053_ & _014_);
  assign ball_bounce_paddle = 1'h1;
  assign bounce_ball_pos_x = { in_ball_pos_x[7], out_ball_pos_x[6:0] };
  assign bounce_ball_pos_y = { in_ball_pos_y[7], out_ball_pos_y[6:0] };
  assign bounce_ball_x = \bouncer_ball_x.bounce ;
  assign bounce_ball_y = \bouncer_ball_y.bounce ;
  assign \bouncer_ball_x.in_pos  = in_ball_pos_x;
  assign \bouncer_ball_x.in_vel  = in_ball_vel_x;
  assign \bouncer_ball_x.near_bound [6:0] = { \bouncer_ball_x.near_bound [7], \bouncer_ball_x.near_bound [7], \bouncer_ball_x.near_bound [7], \bouncer_ball_x.near_bound [7], \bouncer_ball_x.near_bound [7], \bouncer_ball_x.near_bound [7], 1'h1 };
  assign \bouncer_ball_x.out_pos  = { in_ball_pos_x[7], out_ball_pos_x[6:0] };
  assign \bouncer_ball_y.in_pos  = in_ball_pos_y;
  assign \bouncer_ball_y.in_vel  = in_ball_vel_y;
  assign \bouncer_ball_y.near_bound [6:0] = { \bouncer_ball_y.near_bound [7], \bouncer_ball_y.near_bound [7], \bouncer_ball_y.near_bound [7], \bouncer_ball_y.near_bound [7], \bouncer_ball_y.near_bound [7], \bouncer_ball_y.near_bound [7], 1'h1 };
  assign \bouncer_ball_y.out_pos  = { in_ball_pos_y[7], out_ball_pos_y[6:0] };
  assign gutter_ball = 1'h0;
  assign out_ball_pos_x[7] = in_ball_pos_x[7];
  assign out_ball_pos_y[7] = in_ball_pos_y[7];
  assign out_paddle_1_pos = in_paddle_1_pos;
  assign out_paddle_2_pos = 8'hxx;
  assign out_score_p1 = in_score_p1;
  assign out_score_p2 = in_score_p2;
  assign \paddle1.bouncer_paddle.bounce  = 1'h0;
  assign \paddle1.bouncer_paddle.in_pos  = in_paddle_1_pos;
  assign \paddle1.bouncer_paddle.in_vel  = 4'b0x00;
  assign \paddle1.bouncer_paddle.near_bound  = 8'bxxxxxxx1;
  assign \paddle1.bouncer_paddle.new_pos  = in_paddle_1_pos;
  assign \paddle1.bouncer_paddle.out_pos  = in_paddle_1_pos;
  assign \paddle1.in_control  = in_control_1;
  assign \paddle1.in_control_1  = 1'hx;
  assign \paddle1.in_pos  = in_paddle_1_pos;
  assign \paddle1.in_vel  = 4'b0x00;
  assign \paddle1.out_pos  = in_paddle_1_pos;
endmodule
